version: '3.5'
services:
  protocol:
    image: protocol
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - type: bind
        source: logs
        target: /app/logs
